# Generated by Django 4.1.5 on 2023-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
