# Generated by Django 4.1.5 on 2023-01-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0002_cart_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
