# Generated by Django 4.1.5 on 2023-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0003_remove_cart_is_valid_remove_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
