# Generated by Django 4.1.5 on 2023-01-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField()),
                ('unit', models.CharField(choices=[('Kilogramme', 'Kilogramme'), ('Gramme', 'Gramme'), ('Unité', 'Unité')], default='Kilogramme', max_length=50)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='media/products')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('end_shopping_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product_stockitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producteur.product')),
            ],
        ),
    ]
