# Generated by Django 4.1.5 on 2023-01-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producteur.week'),
        ),
    ]
