# Generated by Django 4.1.5 on 2023-01-23 18:14

from django.db import migrations, models
import django.db.models.deletion
import producteur.models


class Migration(migrations.Migration):

    dependencies = [
        ('producteur', '0002_stockitem_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'get_latest_by': 'created_date'},
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='week',
            field=models.ForeignKey(default=producteur.models.get_week, on_delete=django.db.models.deletion.CASCADE, to='producteur.week'),
        ),
    ]
