# Generated by Django 4.1.5 on 2023-01-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteur', '0003_alter_week_options_alter_stockitem_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kilogramme', 'Kg'), ('Gramme', 'G'), ('Unité', 'Pce')], default='Kilogramme', max_length=50),
        ),
    ]
