# Generated by Django 4.1.5 on 2023-01-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteur', '0004_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('G', 'G'), ('Pce', 'Pce')], default='Kg', max_length=50),
        ),
    ]
